### ISSUE TITLE
Get-AzStorageUsage is using wrong API version - Get-AzStorageUsage : The resource type 'locations' could not be found in the namespace 'Microsoft.Storage' for api version '2018-11-01'

### ISSUE THREAD

**Issue by cblackuk** [Azure/azurestack-powershell#43]
Get-AzStorageUsage does not work on Azure Stack Hub because it is using `2018-11-01` API.

The supported api-versions are '2017-10-01,2017-06-01,2016-12-01,2016-05-01,2016-01-01,2015-06-15'.

```powershell
DEBUG: 11:46:02 AM - GetAzureStorageUsageCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 11:46:02 AM - using account id '500a25f0-6350-4a03-8036-b987d81395c4'...
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.x.x.x.x/subscriptions/x-x-x-x-x/providers/Microsoft.Storage/locations/x/usages?api-version=2018-11-01

x-ms-client-request-id        : b03ba5e8-83f1-4a92-ae05-x
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 5490307e-d07e-4ffc-9791-x
x-ms-correlation-request-id   : 5490307e-d07e-4ffc-9791-x
x-ms-routing-request-id       : x:20200807T104602Z:5490307e-d07e-4ffc-9791-0efacbf969f4
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Fri, 07 Aug 2020 10:46:02 GMT

Body:
{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type 'locations' could not be found in the namespace 'Microsoft.Storage' for api version '2018-11-01'. The supported api-versions are '2017-10-01,2017-06-01,2016-12-01,2016-05-01,2016-01-01,2015-06-15'."
  }
}

Get-AzStorageUsage : The resource type 'locations' could not be found in the namespace 'Microsoft.Storage' for api version '2018-11-01'. The supported api-versions are '2017-10-01,2017-06-01,2016-12-01,2016-05-01,2016-01-01,2015-06-15'.
At line:1 char:1
+ Get-AzStorageUsage -Location "x"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzStorageUsage], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.StorageAccount.GetAzureStorageUsageCommand

DEBUG: AzureQoSEvent: CommandName - Get-AzStorageUsage; IsSuccess - False; Duration - 00:00:00.2250584;; Exception - Microsoft.Rest.Azure.CloudException: The resource type 'locations' could not be found in the namespace 'Microsoft.Storage' for api
version '2018-11-01'. The supported api-versions are '2017-10-01,2017-06-01,2016-12-01,2016-05-01,2016-01-01,2015-06-15'.
   at Microsoft.Azure.Management.Storage.UsagesOperations.<ListByLocationWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Storage.UsagesOperationsExtensions.<ListByLocationAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Storage.UsagesOperationsExtensions.ListByLocation(IUsagesOperations operations, String location)
   at Microsoft.Azure.Commands.Management.Storage.StorageAccount.GetAzureStorageUsageCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 11:46:03 AM - GetAzureStorageUsageCommand end processing.
```

```powershell
PS C:\AzureStackDeployment\modules> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.0.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     0.10.0     Az.Compute                          {Add-AzContainerServiceAgentPoolProfile, Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent...}
Script     0.10.0     Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendHttpSetting, Add-AzApplicationGatewayFrontendIPConfig...}
Script     1.2.0      Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Get-AzADAppCredential, Get-AzADApplication...}
Script     1.1.0      Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Disable-AzStorageDeleteRetentionPolicy...}
```

**Comment by cblackuk** [comment]
Damn... this works on 0.10.0 version, which we cannot use because that one does not work with AzTable so we are in a pickle here. Though it is not really an issue with this repo at this point. Closing
